// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ListAccountsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsReq) Reset()         { *m = ListAccountsReq{} }
func (m *ListAccountsReq) String() string { return proto.CompactTextString(m) }
func (*ListAccountsReq) ProtoMessage()    {}
func (*ListAccountsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *ListAccountsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsReq.Unmarshal(m, b)
}
func (m *ListAccountsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsReq.Marshal(b, m, deterministic)
}
func (m *ListAccountsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsReq.Merge(m, src)
}
func (m *ListAccountsReq) XXX_Size() int {
	return xxx_messageInfo_ListAccountsReq.Size(m)
}
func (m *ListAccountsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsReq proto.InternalMessageInfo

type ListAccountsRes struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRes) Reset()         { *m = ListAccountsRes{} }
func (m *ListAccountsRes) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRes) ProtoMessage()    {}
func (*ListAccountsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *ListAccountsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRes.Unmarshal(m, b)
}
func (m *ListAccountsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRes.Marshal(b, m, deterministic)
}
func (m *ListAccountsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRes.Merge(m, src)
}
func (m *ListAccountsRes) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRes.Size(m)
}
func (m *ListAccountsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRes proto.InternalMessageInfo

func (m *ListAccountsRes) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateAccountReq struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountReq) Reset()         { *m = CreateAccountReq{} }
func (m *CreateAccountReq) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReq) ProtoMessage()    {}
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *CreateAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountReq.Unmarshal(m, b)
}
func (m *CreateAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountReq.Marshal(b, m, deterministic)
}
func (m *CreateAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountReq.Merge(m, src)
}
func (m *CreateAccountReq) XXX_Size() int {
	return xxx_messageInfo_CreateAccountReq.Size(m)
}
func (m *CreateAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountReq proto.InternalMessageInfo

func (m *CreateAccountReq) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateAccountRes struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRes) Reset()         { *m = CreateAccountRes{} }
func (m *CreateAccountRes) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRes) ProtoMessage()    {}
func (*CreateAccountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *CreateAccountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRes.Unmarshal(m, b)
}
func (m *CreateAccountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRes.Marshal(b, m, deterministic)
}
func (m *CreateAccountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRes.Merge(m, src)
}
func (m *CreateAccountRes) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRes.Size(m)
}
func (m *CreateAccountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRes proto.InternalMessageInfo

func (m *CreateAccountRes) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type ReadAccountReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountReq) Reset()         { *m = ReadAccountReq{} }
func (m *ReadAccountReq) String() string { return proto.CompactTextString(m) }
func (*ReadAccountReq) ProtoMessage()    {}
func (*ReadAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *ReadAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountReq.Unmarshal(m, b)
}
func (m *ReadAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountReq.Marshal(b, m, deterministic)
}
func (m *ReadAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountReq.Merge(m, src)
}
func (m *ReadAccountReq) XXX_Size() int {
	return xxx_messageInfo_ReadAccountReq.Size(m)
}
func (m *ReadAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountReq proto.InternalMessageInfo

func (m *ReadAccountReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadAccountRes struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountRes) Reset()         { *m = ReadAccountRes{} }
func (m *ReadAccountRes) String() string { return proto.CompactTextString(m) }
func (*ReadAccountRes) ProtoMessage()    {}
func (*ReadAccountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *ReadAccountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountRes.Unmarshal(m, b)
}
func (m *ReadAccountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountRes.Marshal(b, m, deterministic)
}
func (m *ReadAccountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountRes.Merge(m, src)
}
func (m *ReadAccountRes) XXX_Size() int {
	return xxx_messageInfo_ReadAccountRes.Size(m)
}
func (m *ReadAccountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountRes proto.InternalMessageInfo

func (m *ReadAccountRes) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "proto.Account")
	proto.RegisterType((*ListAccountsReq)(nil), "proto.ListAccountsReq")
	proto.RegisterType((*ListAccountsRes)(nil), "proto.ListAccountsRes")
	proto.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "proto.HelloReply")
	proto.RegisterType((*CreateAccountReq)(nil), "proto.CreateAccountReq")
	proto.RegisterType((*CreateAccountRes)(nil), "proto.CreateAccountRes")
	proto.RegisterType((*ReadAccountReq)(nil), "proto.ReadAccountReq")
	proto.RegisterType((*ReadAccountRes)(nil), "proto.ReadAccountRes")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0x03, 0xb6, 0x45, 0xa7, 0x15, 0x75, 0xe2, 0x1f, 0xc2, 0xa9, 0xd9, 0x83, 0xe9, 0xa9,
	0x31, 0xf5, 0x66, 0x3d, 0x68, 0xbc, 0x68, 0xe2, 0x09, 0x1f, 0xc0, 0xac, 0xec, 0xc4, 0x6c, 0x02,
	0xe5, 0xcf, 0x80, 0xc6, 0xa7, 0xf0, 0x95, 0x8d, 0xcb, 0x62, 0x90, 0xf6, 0xc2, 0x09, 0xbe, 0xdf,
	0x7c, 0x33, 0xf3, 0x6d, 0x06, 0x0e, 0x65, 0x1c, 0x67, 0xf5, 0xa6, 0x5a, 0xe6, 0x65, 0x56, 0x65,
	0x38, 0x36, 0x1f, 0xa1, 0xc0, 0xbb, 0x6f, 0x38, 0xfa, 0xe0, 0x6a, 0x15, 0x38, 0x73, 0x67, 0x71,
	0x10, 0xb9, 0x5a, 0xe1, 0x05, 0x78, 0x35, 0x53, 0xf9, 0xaa, 0x55, 0xe0, 0x1a, 0x38, 0xf9, 0x95,
	0x4f, 0x0a, 0x4f, 0x61, 0x4c, 0xa9, 0xd4, 0x49, 0xb0, 0x67, 0x70, 0x23, 0x30, 0x84, 0xfd, 0x5c,
	0x32, 0x7f, 0x66, 0xa5, 0x0a, 0x46, 0xa6, 0xf0, 0xa7, 0xc5, 0x09, 0x1c, 0x3d, 0x6b, 0xae, 0xec,
	0x26, 0x8e, 0xa8, 0x10, 0xeb, 0x3e, 0x62, 0x5c, 0x80, 0x67, 0x33, 0x9a, 0x14, 0xd3, 0x95, 0xdf,
	0x64, 0x5d, 0x5a, 0x53, 0xd4, 0x96, 0x85, 0x80, 0xd9, 0x23, 0x25, 0x49, 0x16, 0x51, 0x51, 0x13,
	0x57, 0x88, 0x30, 0xda, 0xc8, 0x94, 0x6c, 0x78, 0xf3, 0x2f, 0x2e, 0x01, 0xac, 0x27, 0x4f, 0xbe,
	0x30, 0x00, 0x2f, 0x25, 0x66, 0xf9, 0xde, 0x9a, 0x5a, 0x29, 0x6e, 0xe1, 0xf8, 0xa1, 0x24, 0x59,
	0x51, 0xbb, 0x85, 0x8a, 0x01, 0x49, 0xb6, 0xbb, 0x87, 0xbc, 0x63, 0x0e, 0x7e, 0x44, 0x52, 0x75,
	0x36, 0xf7, 0x8e, 0x20, 0x6e, 0x7a, 0x8e, 0x01, 0xd3, 0x57, 0xdf, 0x0e, 0xf8, 0x16, 0xbe, 0x50,
	0xf9, 0xa1, 0x63, 0xc2, 0x35, 0x4c, 0x3b, 0xe3, 0xf0, 0xcc, 0xb6, 0xfe, 0x0f, 0x11, 0xee, 0xc4,
	0x8c, 0x77, 0x30, 0xeb, 0x9e, 0x0c, 0xcf, 0xad, 0xad, 0x77, 0xda, 0x70, 0x37, 0xe7, 0x2b, 0xe7,
	0x6d, 0x62, 0x0a, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x9c, 0xc1, 0xf1, 0x8c, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	ReadAccount(ctx context.Context, in *ReadAccountReq, opts ...grpc.CallOption) (*ReadAccountRes, error)
	ListAccounts(ctx context.Context, in *ListAccountsReq, opts ...grpc.CallOption) (AccountService_ListAccountsClient, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) ReadAccount(ctx context.Context, in *ReadAccountReq, opts ...grpc.CallOption) (*ReadAccountRes, error) {
	out := new(ReadAccountRes)
	err := c.cc.Invoke(ctx, "/proto.AccountService/ReadAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListAccounts(ctx context.Context, in *ListAccountsReq, opts ...grpc.CallOption) (AccountService_ListAccountsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AccountService_serviceDesc.Streams[0], "/proto.AccountService/ListAccounts", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountServiceListAccountsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AccountService_ListAccountsClient interface {
	Recv() (*ListAccountsRes, error)
	grpc.ClientStream
}

type accountServiceListAccountsClient struct {
	grpc.ClientStream
}

func (x *accountServiceListAccountsClient) Recv() (*ListAccountsRes, error) {
	m := new(ListAccountsRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	ReadAccount(context.Context, *ReadAccountReq) (*ReadAccountRes, error)
	ListAccounts(*ListAccountsReq, AccountService_ListAccountsServer) error
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) ReadAccount(ctx context.Context, req *ReadAccountReq) (*ReadAccountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAccount not implemented")
}
func (*UnimplementedAccountServiceServer) ListAccounts(req *ListAccountsReq, srv AccountService_ListAccountsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_ReadAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ReadAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/ReadAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ReadAccount(ctx, req.(*ReadAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListAccountsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountServiceServer).ListAccounts(m, &accountServiceListAccountsServer{stream})
}

type AccountService_ListAccountsServer interface {
	Send(*ListAccountsRes) error
	grpc.ServerStream
}

type accountServiceListAccountsServer struct {
	grpc.ServerStream
}

func (x *accountServiceListAccountsServer) Send(m *ListAccountsRes) error {
	return x.ServerStream.SendMsg(m)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAccount",
			Handler:    _AccountService_ReadAccount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAccounts",
			Handler:       _AccountService_ListAccounts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "account.proto",
}
